language: php
sudo: false
dist: trusty
php:
  - 7.2
cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.composer/cache
    - $HOME/.npm
before_script:
  - composer self-update
  - composer update
  - composer global require phpstan/phpstan
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - composer analyze
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
